version: '3'

services:
  app:
    build:
      context: app
    restart: always
    networks:
      - internal
    ports: 
      - "3000:3000"
    environment:
      APPFLAG: zeroday{4rchm4g3_1s_4rch41c}
  bot:
    build:
      context: bot
      args:
        - BROWSER=chromium
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://app/
      APPURLREGEX: ^http(|s)://.*$
      APPFLAG: zeroday{4rchm4g3_1s_4rch41c}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
    ports:
      - "80:3000"
    networks:
      - internal

networks:
  internal:
